### ISSUE TITLE
Good to see these kinda activities here from you dude!

### ISSUE THREAD

**Issue by praserocking** [shiv6146/dynamic-memory-allocator#1]
But, again there comes the notification about you following "someone", which spoils the fun. Or adds to the fun? :-D

**Comment by shiv6146** [comment]
@praserocking Dei dei yen da intha kolaveri! Nane enoda course assignments ah git la push pantu iruken avlo than..! And the following someone kum ithukum entha oru samantham illai :stuck_out_tongue_winking_eye:
